// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginSession struct {
	LoginName string `json:"loginName"`
	Password  string `json:"password"`
}

type NewComment struct {
	UserID  int     `json:"userId"`
	PostID  int     `json:"postId"`
	Content *string `json:"content"`
}

type NewPost struct {
	UserID  int     `json:"userId"`
	Title   *string `json:"title"`
	Content *string `json:"content"`
}

type NewUser struct {
	LoginName string `json:"loginName"`
	Password  string `json:"password"`
}

type UpdateComment struct {
	CommentID int     `json:"commentId"`
	Content   *string `json:"content"`
}

type UpdatePost struct {
	PostID  int     `json:"postId"`
	Title   *string `json:"title"`
	Content *string `json:"content"`
}
