package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
)

// FileUpload is the resolver for the fileUpload field.
func (r *mutationResolver) FileUpload(ctx context.Context, file graphql.Upload) (bool, error) {
	panic(fmt.Errorf("not implemented: FileUpload - fileUpload"))
}
