package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"backend/pkg/db"
	"backend/pkg/gql/graph/model"
	"context"
	"time"

	"golang.org/x/crypto/bcrypt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*db.User, error) {
	pw, err := bcrypt.GenerateFromPassword([]byte(input.Password), 0)
	if err != nil {
		return nil, err
	}

	user := &db.User{
		LoginName: input.LoginName,
		Password:  string(pw),
	}

	_, err = r.DB.NewInsert().Model(user).Returning("*").Exec(ctx)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*db.Post, error) {
	post := &db.Post{
		UserID:  int32(input.UserID),
		Content: *input.Content,
		Title:   *input.Title,
	}
	_, err := r.DB.NewInsert().Model(post).Returning("*").Exec(ctx)
	if err != nil {
		return nil, err
	}
	return post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.NewComment) (*db.Comment, error) {
	comment := &db.Comment{
		UserID:  int32(input.UserID),
		PostID:  int32(input.PostID),
		Content: *input.Content,
	}
	_, err := r.DB.NewInsert().Model(comment).Returning("*").Exec(ctx)
	if err != nil {
		return nil, err
	}
	return comment, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, input int) (bool, error) {
	_, err := r.DB.NewDelete().Model((*db.User)(nil)).Where("user_id = ?", input).Exec(ctx)
	if err != nil {
		return false, err
	}
	return true, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, input int) (bool, error) {
	_, err := r.DB.NewDelete().Model((*db.Post)(nil)).Where("post_id = ?", input).Exec(ctx)
	if err != nil {
		return false, err
	}
	return true, nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, input int) (bool, error) {
	_, err := r.DB.NewDelete().Model((*db.Comment)(nil)).Where("comment_id = ?", input).Exec(ctx)
	if err != nil {
		return false, err
	}
	return true, nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePost) (*db.Post, error) {
	post := &db.Post{
		ID:        int32(input.PostID),
		UpdatedAt: time.Now(),
	}

	if input.Content != nil {
		post.Content = *input.Content
	}

	if input.Title != nil {
		post.Title = *input.Title
	}

	_, err := r.DB.NewUpdate().Model(post).OmitZero().WherePK().Returning("*").Exec(ctx)
	if err != nil {
		return nil, err
	}
	return post, nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, input model.UpdateComment) (*db.Comment, error) {
	comment := &db.Comment{
		ID:        int32(input.CommentID),
		UpdatedAt: time.Now(),
	}

	if input.Content != nil {
		comment.Content = *input.Content
	}
	_, err := r.DB.NewUpdate().Model(comment).OmitZero().WherePK().Returning("*").Exec(ctx)
	if err != nil {
		return nil, err
	}
	return comment, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, input model.GetUserInput) ([]db.User, error) {
	var users []db.User
	err := r.DB.NewSelect().Model(&users).Relation("Post").Relation("Comment").
		Order(input.OrderBy.String() + " " + input.Order.String()).Limit(input.Limit).
		Offset(input.Offset).
		Scan(ctx)
	if err != nil {
		return nil, err
	}

	return users, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, input model.GetPostInput) ([]db.Post, error) {
	var posts []db.Post
	err := r.DB.NewSelect().Model(&posts).Relation("User").Relation("Comment").
		Order(input.OrderBy.String() + " " + input.Order.String()).Limit(input.Limit).
		Offset(input.Offset).Scan(ctx)

	if err != nil {
		return nil, err
	}
	return posts, nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, input model.GetCommentInput) ([]db.Comment, error) {
	var comments []db.Comment
	err := r.DB.NewSelect().Model(&comments).Relation("Post").Relation("User").
		Order(input.OrderBy.String() + " " + input.Order.String()).Limit(input.Limit).
		Offset(input.Offset).Scan(ctx)
	if err != nil {
		return nil, err
	}
	return comments, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
